config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'post/new'

  get 'post/create'

  get 'post/index'

  devise_for :users

resources :relationship, :only => []

get 'relationship/following'
get 'relationship/followers'

get 'relationship/follow', to: "relationship#follow", :as => 'follow'
get 'relationship/unfollow', to: "relationship#unfollow", :as => 'unfollow'

  devise_scope :user do
    authenticated :user do
     root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
     root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  field :message, type: String

 belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  has_many :post
  has_and_belongs_to_many :following, :class_name => 'User', inverse_of: :followers, autosave: true
  has_and_belongs_to_many :followers, :class_name => 'User', inverse_of: :following

  def follow(user)
    if self.id != user.id && !self.following.include?(user)
      self.following << user
    end
  end

  def unfollow(user)
    self.following.delete(user)
  end

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:destroy]

  def index
    @tipo_listagem = params[:list]

    if @tipo_listagem != 'following'
      @posts = Post.includes(:user).order(created_at: :desc)
    else
      @posts = Post.where(:user_id => current_user.id).order(created_at: :desc)

      current_user.following.each do | following |
        @posts = @posts + Post.where(:user_id => following.id).order(created_at: :desc)
      end
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = User.find(current_user.id)

    respond_to do |format|
      if @post.save
        format.html { redirect_to action: "index", notice: 'Post was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Postagem deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:message, :user_id)
    end
end

app/controllers/relationship_controller.rb
class RelationshipController < ApplicationController
  def following
    @users =  current_user.following
    @title = 'Seguindo'
    render 'show_follow'
  end

  def followers
    @users =  current_user.followers
    @title = 'Seguidores'
    render 'show_follow'
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)

    respond_to do | format |
      format.html { redirect_to posts_path, notice: 'Começou a seguir ' + @user.email }
    end
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.unfollow(@user)

    respond_to do | format |
      format.html { redirect_to posts_path, notice: 'Deixou de seguir ' + @user.email }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/views/layouts/_footer.html.erb
</div>

app/views/layouts/_header.html.erb
<div id="wrapper">
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'Twitter Clone', posts_path, class:"navbar-brand" %>
        </div>

        <ul class="nav navbar-top-links navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <%= current_user.email %> <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><%= link_to '<i class="fa fa-user fa-fw"></i> Editar Perfil'.html_safe, edit_user_registration_path %></li>
                    </li>
                    <li class="divider"></li>
                    <li><%=link_to '<i class="fa fa-sign-out fa-fw"></i> Sair'.html_safe, destroy_user_session_path, :method => :delete %></li>
                </ul>
            </li>
        </ul>
    </nav>

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <%= link_to '<i class="fa fa-files-o fa-fw"></i> Todas as postagens'.html_safe, posts_path(list: 'all') %>
                </li>
                <li>
                    <%= link_to '<i class="fa fa-files-o fa-fw"></i> Postagens dos meus seguidos'.html_safe, posts_path(list: 'following') %>
                </li>
                <li>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-red">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <i class="fa fa-support fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge"><%= current_user.following.count %></div>

                                                <div>Seguindo</div>
                                            </div>
                                        </div>
                                    </div>
                                    <%= link_to  '<div class="panel-footer">
                                                              <span class="pull-left">Ver Todos</span>
                                                              <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                                              <div class="clearfix"></div>
                                                          </div>'.html_safe, relationship_following_path, method: :get %>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="panel panel-green">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-xs-3">
                                                <i class="fa fa-support fa-5x"></i>
                                            </div>
                                            <div class="col-xs-9 text-right">
                                                <div class="huge"><%= current_user.followers.count %></div>

                                                <div>Seguidores</div>
                                            </div>
                                        </div>
                                    </div>
                                    <%= link_to  '<div class="panel-footer">
                                                              <span class="pull-left">Ver Todos</span>
                                                              <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                                              <div class="clearfix"></div>
                                                          </div>'.html_safe, relationship_followers_path, method: :get %>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TwitterClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= yield %>
</body>

</html>

app/views/posts/_form.html.erb
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Novo tweet</h4>
</div>

<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div class="modal-body">
          <form role="form">
              <div class="form-group">
                  <label><%= form.label :message %></label>
                  <%= form.text_area :message, id: :post_message, :rows => 4, class:"form-control", id: 'text-message' %>
                  <div id="charNum"></div>
              </div>
              <div class="modal-footer">
                  <div class="actions">
                      <%= link_to 'Voltar', posts_path, class:"btn btn-default" %>
                      <%= form.submit "Postar", class:"btn btn-success"%>
                  </div>
              </div>
          </form>
      </div>
<% end %>
<script>
  $(document).ready( function() {
          var maxLen = 155;

          $('#text-message').keypress(function(event){
              var Length = $("#text-message").val().length;
              var AmountLeft = maxLen - Length;
              $('#txt-length-left').html(AmountLeft);
              if(Length >= maxLen){
                  if (event.which != 8) {
                      return false;
                  }
              }

               var char = (maxLen - Length) - 1;
              $('#charNum').text(char + ' caracteres restantes.');
          });

  });
</script>

app/views/posts/index.html.erb
<%= render partial: "layouts/header" %>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <br />
                <% unless notice.nil? %>
                  <p id="notice" class="alert alert-success"><%= notice %></p>
                <% end %>
                <h1 class="page-header">Postagens <%= link_to 'Novo Tweet', new_post_path, data: {toggle: "modal", target: "#my-modal"}, class:"btn btn-default" %></h1>

                <div class="modal fade" id="my-modal" tabindex="-1" role="dialog" aria-labelledby="my-modalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                        </div>
                    </div>
                </div>

                <% @posts.each do |post| %>
                  <div class="row">
                      <div class="col-lg-12">
                          <div class="panel panel-default">
                              <div class="panel-heading">
                                  <%= post.user.email %>

                                  <% @found_one = false %>
                                  <% if current_user.id != post.user.id %>
                                      <% current_user.following.each do | following | %>
                                          <% if following.id == post.user.id %>
                                              <% @found_one = true %>
                                          <% end %>
                                      <% end %>
                                      <% if @found_one %>
                                          <%= link_to "Deixar de Seguir", unfollow_path(id: post.user.id), class: "btn btn-outline btn-danger" %>
                                      <% else %>
                                          <%= link_to "Seguir", follow_path(id: post.user.id), class: "btn btn-outline btn-success" %>
                                       <% end %>
                                  <% end %>
                              </div>
                              <div class="panel-body">
                                  <p><%= post.message %></p>
                              </div>
                              <div class="panel-footer">
                                  <span class="glyphicon glyphicon-time"></span> <%= post.created_at.strftime("Postado em: %d/%m/%Y as %H:%M") %>

                                  <% if current_user.id == post.user.id %>
                                      <%= link_to 'Deletar', '#', data: {toggle: "modal", target: "#myModal"}, class:"btn btn-danger" %>

                                      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal" aria-hidden="true">
                                          <div class="modal-dialog">
                                              <div class="modal-content">
                                                  <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                      <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
                                                  </div>
                                                  <div class="modal-body">
                                                      Tem certeza que deseja deletar este tweet?
                                                  </div>
                                                  <div class="modal-footer">
                                                      <button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
                                                      <%= link_to("Sim, tenho certeza", post, method: :delete, class: 'btn btn-primary') %>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                  <% end %>
                              </div>
                          </div>
                      </div>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<%= render partial: "layouts/footer" %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/relationship/show_follow.html.erb
<%= render partial: "layouts/header" %>
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"><%= @title %></h1>

                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="list-group">
                                <% @users.each do | user | %>
                                  <a href="#" class="list-group-item">
                                      <i class="fa fa-user fa-fw"></i> <%= user.email %>
                                      <span class="pull-right text-muted small"><em><%= user.last_sign_in_at.strftime("Último acesso em: %d/%m/%Y as %H:%M") %></em>
                                      </span>
                                  </a>
                                <% end %>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>
<%= render partial: "layouts/footer" %>